### PR TITLE
New layout with light/dark modes 

### PR DESCRIPTION
**Pull request by Labryn**
#66 

I also changed the logo to a black and white logo, but that was just an idea, obviously change it back if you'd like. The other change would be taking it to 2.5.0.

### CODE REVIEW

**Comment by az0** [comment]
@Labryn 
Thank you

Are these duplicate files that can be combined?

```
./icons/logo-black-16.png
./icons/logo-black-128.png
./icons/logo-black-48.png
./browser/assets/logo-black-16.png
./browser/assets/logo-black-128.png
./browser/assets/logo-black.png
./browser/assets/logo-black-48.png
````

**Comment by az0** [comment]
@Labryn 
Disregard my  last comment. I made the change here https://github.com/az0/linkgopher/commit/c8de85b05808d88a3ce2370e7becf4804a3297db

**Comment by az0** [comment]
@Labryn 
Are you interested in helping to[ make these screenshots](https://github.com/az0/linkgopher/issues/69)?

**Comment by az0** [comment]
After publishing this on Mozilla (but not Google), two issues were filed

https://github.com/az0/linkgopher/issues/71
https://github.com/az0/linkgopher/issues/70

There were [three negative reviews](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/reviews/) recently on Mozilla

One

>It was great until the recent update. Now I have to delete empty lines between results which is extremely annoying, and it takes twice as much scrolling down to select all links that you need to copy. Also the new icon's visibility is much worse.

Two

>The new update has ruined this add on. The new theme has killed the ability to copy and paste links properly making this add on completely useless now. Dont fix things that arent broken!

Three

>This previously-5star extension has been completely changed for the worse in the latest update.

>The generated output is now full of additional line-breaks, making copy (and paste into another app) a pain - arguably the entire point of it existing and working in the way it does, given that there's no export functionality. Furthermore, the output now has full-width clickable links, making it far too easy to accidentally click a link when dragging to select multiple links. It was previously a simple HTML text page with the links on a new line. Even the icon has changed (where it's now one which looks like the Firefox profile icon, and I didn't even see it and assumed the extension had been removed at first).

>Yet in spite of these visual changes, no beneficial, functional changes as far as I can see. Why on earth does such a simple tool need a "dark mode" anyway, and who cares what the output looks like? Such a shame. I'll be forcing install of the previous 2.5.0 release on my machines because 2.6.1 is pretty much unusable.

There were no positive responses, for now I am going to revert the changes. I do like the idea that users can choose a theme, but we need to consider the comments and provide a better default experience.

**Comment by Taraman17** [comment]
I completely go with the negative reviews. All those extra empty lines when pasting longer lists is a pain.

If you stick with the new design for clickable links, please add an option to get an unformatted list.

**Comment by Labryn** [comment]
@az0 @Taraman17 @jwilk @benzBrake 


> After publishing this on Mozilla (but not Google), two issues were filed
> 
> #71 #70
> 
> There were [three negative reviews](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/reviews/) recently on Mozilla
> 
> One
> 
> > It was great until the recent update. Now I have to delete empty lines between results which is extremely annoying, and it takes twice as much scrolling down to select all links that you need to copy. Also the new icon's visibility is much worse.
> 
> Two
> 
> > The new update has ruined this add on. The new theme has killed the ability to copy and paste links properly making this add on completely useless now. Dont fix things that arent broken!
> 
> Three
> 
> > This previously-5star extension has been completely changed for the worse in the latest update.
> 
> > The generated output is now full of additional line-breaks, making copy (and paste into another app) a pain - arguably the entire point of it existing and working in the way it does, given that there's no export functionality. Furthermore, the output now has full-width clickable links, making it far too easy to accidentally click a link when dragging to select multiple links. It was previously a simple HTML text page with the links on a new line. Even the icon has changed (where it's now one which looks like the Firefox profile icon, and I didn't even see it and assumed the extension had been removed at first).
> 
> > Yet in spite of these visual changes, no beneficial, functional changes as far as I can see. Why on earth does such a simple tool need a "dark mode" anyway, and who cares what the output looks like? Such a shame. I'll be forcing install of the previous 2.5.0 release on my machines because 2.6.1 is pretty much unusable.
> 
> Four
> 
> > The first rule of computing is never fix what ain't broken and sadly Andrew has broken that rule. The new presentation of results is awful. Not only does it gratuitously double the size of the report by putting blank lines between each entry but the entry lines are obscured by a grey background making them much harder to read to the point where I'm considering looking for a different tool.
> 
> > Link Gopher has been a core tool for me for many years but unless this new report is scrapped and replaced with something comparable to the original basic text report I'll be looking for a new tool. Perhaps providing a setting to switch off the presentation formatting is the answer?
> 
> > Equally changing the icon is not a smart move either because i spent an hour looking for where it disappeared to before realising that it had been changed to what is a far less recognisable design. Using grey again is a bad idea. Change it to a more vibrant dark background colour and make the whole thing bigger so that the white links can be seen. It just looks like a grey blob on my menu line currently.
> 
> There were no positive responses, for now I am going to revert the changes. I do like the idea that users can choose a theme, but we need to consider the comments and provide a better default experience.

I'm SOOOOO very sorry this has happened. I understand that this is my fault. I originally wanted to do this as a private project until I noticed a few others asking for a dark mode which is exactly what I wanted and was privately designing as a personal/learning exercise, and then I thought my screenshots along with pull request note about the logo/version change had been welcomed, however, I was being too proud and confident in myself that I disregarded other users of this great tool and the many ways it was being used.

I apologize for messing up such a great tool and upsetting everyone.

I'm willing to help fix my mistake to make as many happy as possible, but I understand if that is not wanted from me at this point. Sorry again to everyone upset and negatively affected by my changes.

**Comment by Taraman17** [comment]
Hey, don't be too hard on yourself.
The new design looks a lot nicer than the old one. Unfortunately for you, people (including me) seem to use it differently than you thought. Copying these links to use them directly elsewhere is the main thing I love about this plugin.

So realizing and even better admitting that you went in a direction many users don't like is a good thing.
So please keep on working on this!

My suggestion would be to offer a dark design, that keeps the simplicity of the old one.
Since you won't want to discard your recent work, keep the new eyecandy and make it configurable to the user which one he wants to use.

Just my 22 cents of course...

**Comment by jantje** [comment]
I agree with @Taraman17 here:.
As he said: "Don't be to hard on yourself." You have stepped forward to improve other peoples life. That is a good thing.
Now you learned that "improve" is a very personal thing.
Life is a learning experience. We also learned that there are at least 2 types of users of this tool. 
1)The people only interested in extracting links who are very happy with default html basic behaviour (like me) and 
2) people wanting a nicer user experience.
Adding a option to switch between one of the 2 seems the best way to satisfy both user groups.

Just my 2 cents of course...

**Pull request merged**
