### PR TITLE
Implement keyboard shortcuts (commands).

### LINKED ISSUE #42: Keyboard shortcuts

### PR DESCRIPTION
**Pull request by jtagcat**
Closes #42

### CODE REVIEW

**Review by az0 — CHANGES_REQUESTED** [review]
Thanks.

Would you also provide documentation for end users? Even if it is very short, that would be appreciated.

**Comment by az0** [comment]
@jtagcat 

Are you able to please help make this compatible with Chromium-based browsers (e.g., Google Chrome)? It doesn't have to enable the keyboard shortcuts on Chromium, but as it is now, the extension totally fails to work.

Related issue https://github.com/az0/linkgopher/issues/47

**Comment by az0** [comment]
I had to revert this for Firefox because it [broke the extension](https://github.com/az0/linkgopher/issues/48) for some FIrefox users

**Comment by lutzd** [comment]
hallo my dear
when deactivate xpi certification check, my linkgopher works fine, Thank you!!

screenshot 269

**Pull request merged**
